name: manhattan_gold_coin_wallt
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  provider: ^6.1.2
  dio: ^5.5.0+1
  flutter_secure_storage: ^9.2.2
  ed25519_hd_key: ^2.2.0
  hex: ^0.2.0
  shared_preferences: ^2.2.3
  bitcoin_base: ^4.7.0
  audioplayers: ^3.0.0
  flutter_barcode_scanner: ^2.0.0
  base58check: ^2.0.0
  logger: ^2.4.0
  blockchain_utils: ^3.3.0
  bip39: ^1.0.6
  scrypt: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.0
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/coin.jpeg"

flutter_native_splash:
  color: "#FFD700" # Gold color
  image: 'assets/icons/coin.jpeg'
  android: true
  ios: true
  web: false
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/sound.mp3
    - assets/icons/coin.jpeg
